"""empty message

Revision ID: 346eaafeb42a
Revises: d815d6f1d568
Create Date: 2021-12-20 22:57:27.479371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346eaafeb42a'
down_revision = 'd815d6f1d568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('height', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=150), nullable=True),
    sa.Column('homeworld', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('population', table_name='planet')
    op.drop_index('population_2', table_name='planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('population_2', 'planet', ['population'], unique=False)
    op.create_index('population', 'planet', ['population'], unique=False)
    op.drop_table('people')
    op.drop_table('favorite')
    # ### end Alembic commands ###
