"""empty message

Revision ID: 4732fd2b9736
Revises: 4c886a2e4af9
Create Date: 2021-12-22 22:03:57.068644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4732fd2b9736'
down_revision = '4c886a2e4af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password2', sa.String(length=250), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('user', 'password2')
    # ### end Alembic commands ###
