"""empty message

Revision ID: 4c886a2e4af9
Revises: f0f1cc986081
Create Date: 2021-12-21 02:07:34.164988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c886a2e4af9'
down_revision = 'f0f1cc986081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'population',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('planet', 'climate',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'climate',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('planet', 'population',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
