"""empty message

Revision ID: 6034a9b7e2cf
Revises: 4732fd2b9736
Create Date: 2021-12-22 22:04:36.605339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6034a9b7e2cf'
down_revision = '4732fd2b9736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=250), nullable=False))
    op.drop_column('user', 'password2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password2', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
