"""empty message

Revision ID: f0f1cc986081
Revises: 346eaafeb42a
Create Date: 2021-12-20 23:11:37.376234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0f1cc986081'
down_revision = '346eaafeb42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favorite', 'planet', ['planet_id'], ['id'])
    op.create_foreign_key(None, 'favorite', 'people', ['people_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
